[tool.poetry]
name = "spak-pdf-tutorials"
version = "0.1.0"
description = ""
authors = ["Mykola Melnyk <kolia1985@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
jupyter = "^1.1.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
